#---
#include:
#  - board: nice_nano_v2
#    shield: dorne_dongle
#
#  - board: nice_nano_v2
#    shield: dorne_left
#    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
#
#  - board: nice_nano_v2
#    shield: dorne_right
#    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
#
#  - board: nice_nano_v2
#    shield: settings_reset

---
include:
  - board: nice_nano_v2
    shield: corne_dongle
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    #artifact-name: nano_dongle

  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    #artifact-name: nano_corne_left

  - board: nice_nano_v2
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    #artifact-name: nano_corne_right

  - board: nice_nano_v2
    shield: settings_reset
    #artifact-name: nano_reset_settings
